src/Entity/Recipe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecipeRepository")
 * <@ORM\HasLifecycleCallbacks()>
 */
class Recipe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="time")
     */
    private $bakingTime;

    /**
     * @ORM\Column(type="time")
     */
    private $preparationTime;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Positive
     */
    private $nbPersonne;
//j'aurais du mettre nbPersons
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Difficulty", inversedBy="recipes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $difficulty;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="recipes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="recipes")
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RecipeIngredient", mappedBy="recipe", orphanRemoval=true)
     */
    private $recipeIngredients;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="recipe", orphanRemoval=true)
     */
    private $photos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Step", mappedBy="recipe", orphanRemoval=true)
     */
    private $steps;
    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="recipes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Feedback", mappedBy="recipe", orphanRemoval=true)
     */
    private $feedbacks;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->recipeIngredients = new ArrayCollection();
        $this->photos = new ArrayCollection();
        $this->steps = new ArrayCollection();
        $this->feedbacks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null-
     */
    public function getBakingTime(): ?\DateTimeInterface
    {
        return $this->bakingTime;
    }

    public function getBakingTimeFormatted(): string
    {
        return $this->formatTime($this->getBakingTime());
    }


    public function setBakingTime(\DateTimeInterface $bakingTime): self
    {
        $this->bakingTime = $bakingTime;

        return $this;
    }

    public function getPreparationTime(): ?\DateTimeInterface
    {
        return $this->preparationTime;
    }

    public function getPreparationTimeFormatted(): string
    {
        //j'appelle ma methode et dans son parametre je mets getpreparationTime
        return $this->formatTime($this->getPreparationTime());
    }



    public function setPreparationTime(\DateTimeInterface $preparationTime): self
    {
        $this->preparationTime = $preparationTime;

        return $this;
    }

    public function getNbPersonne(): ?int
    {
        return $this->nbPersonne;
    }

    public function setNbPersonne(int $nbPersonne): self
    {
        $this->nbPersonne = $nbPersonne;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDifficulty(): ?Difficulty
    {
        return $this->difficulty;
    }

    public function setDifficulty(?Difficulty $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }


    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|RecipeIngredient[]
     */
    public function getRecipeIngredients(): Collection
    {
        return $this->recipeIngredients;
    }

    public function addRecipeIngredient(RecipeIngredient $recipeIngredient): self
    {
        if (!$this->recipeIngredients->contains($recipeIngredient)) {
            $this->recipeIngredients[] = $recipeIngredient;
            $recipeIngredient->setRecipe($this);
        }

        return $this;
    }

    public function removeRecipeIngredient(RecipeIngredient $recipeIngredient): self
    {
        if ($this->recipeIngredients->contains($recipeIngredient)) {
            $this->recipeIngredients->removeElement($recipeIngredient);
            // set the owning side to null (unless already changed)
            if ($recipeIngredient->getRecipe() === $this) {
                $recipeIngredient->setRecipe(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    private function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setRecipe($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getRecipe() === $this) {
                $photo->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Step[]
     */
    public function getSteps(): Collection
    {
        return $this->steps;
    }

    public function addStep(Step $step): self
    {
        if (!$this->steps->contains($step)) {
            $this->steps[] = $step;
            $step->setRecipe($this);
        }

        return $this;
    }

    public function removeStep(Step $step): self
    {
        if ($this->steps->contains($step)) {
            $this->steps->removeElement($step);
            // set the owning side to null (unless already changed)
            if ($step->getRecipe() === $this) {
                $step->setRecipe(null);
            }
        }

        return $this;
    }
    //des qu'on va creer une nouvelle recette, il va remplir le champ avec la date automatiquement
    //grace à @ORM\HasLifecycleCallbacks() en haut (code que l'on va pouvoir exéctuter à un moment dans le code = hook en wordpress)
    //annotation ici = moment où cela va enregistrer
    /**
     * @ORM\PrePersist()
     */
    public function prePersist(){
        $this->setCreatedAt(new \DateTime());
    }

    //methode pour formater classes. Privée parce que pas de raison de la recuperer ailleurs que dans la classe
    private function formatTime(\DateTimeInterface $time): string
    {
        $hours = $time->format("G");
        $minutes = $time->format("i");
        $formattedTime = "";

        if ($hours > 0) {
            $formattedTime = "$hours heure" . (($hours > 1) ? "s" : "");
        }
        $formattedTime .= " ";
        if ($minutes > 0) {
            $formattedTime .= "$minutes minute" . (($minutes > 1) ? "s" : "");
        }

        return trim($formattedTime);
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Feedback[]
     */
    public function getFeedbacks(): Collection
    {
        return $this->feedbacks;
    }

    public function addFeedback(Feedback $feedback): self
    {
        if (!$this->feedbacks->contains($feedback)) {
            $this->feedbacks[] = $feedback;
            $feedback->setRecipe($this);
        }

        return $this;
    }

    public function removeFeedback(Feedback $feedback): self
    {
        if ($this->feedbacks->contains($feedback)) {
            $this->feedbacks->removeElement($feedback);
            // set the owning side to null (unless already changed)
            if ($feedback->getRecipe() === $this) {
                $feedback->setRecipe(null);
            }
        }

        return $this;
    }

    public function __toString()
    {

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Difficulty;
use App\Entity\Recipe;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class,[
                'label' => 'Titre',
                'attr' =>[
                    'placeholder' => 'Titre'
                ]
            ])
            ->add('bakingTime')
            ->add('preparationTime')
            ->add('nbPersonne')
            ->add('pictureFile', FileType::class, [
                //oui je sais que pictureFile n'existe pas dans l'entité dc pas mappé. on fera le lien dans notre code
                'mapped' => false
            ])
            ->add('difficulty')
            ->add('category', EntityType::class,[
        'class' => Category::class,
        'choice_label' => 'label'
    ])
            ->add('tags', EntityType::class,[
                'class' => Tag::class,
                'multiple' => true,
                'expanded' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use App\Service\FileUploader;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

// prefix qui sera mis devant toutes les routes de ce controller
/**
 * @Route("/recipe")
 */
class RecipeController extends AbstractController
{
    /**
     * @Route("/", name="recipe_index", methods={"GET"})
     */

    public function index(RecipeRepository $recipeRepository): Response
    {
        return $this->render('recipe/index.html.twig', [
            'recipes' => $recipeRepository->findAll(),
        ]);
    }

    //il faut etre authentifier pour acceder au new
    //ou possible de mettre $this->>deniedAccessGranteddans methode
    /**
     * @Route("/new", name="recipe_new", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    // injection de dependance/service en rajoutant parametre FileUploader
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $pictureFile */
            $pictureFile = $form['pictureFile']->getData();

            if ($pictureFile) {
                $pictureFilename = $fileUploader->upload($pictureFile);
                $recipe->setPicture($pictureFilename);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $recipe->setUser($this->getUser()); // Associer la recette à l'utilisateur connecté
            $entityManager->persist($recipe);
            $entityManager->flush();

            return $this->redirectToRoute('homepage');
        }

        return $this->render('recipe/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="recipe_show", methods={"GET"})
     */
    public function show(Recipe $recipe): Response
    {
        //$this->getDoctrine->getRepository($classname::class)->findOneById($id);
        // si on voulait mettre un slug dans l'url à la place id, il faudrait créer propriété slug dans l'entity
        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,


        ]);
    }

    /**
     * @Route("/{id}/edit", name="recipe_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, Recipe $recipe): Response
    {
        //verifier si l'utilisateur connecté est admin ou si c'est lui qui a créé la recette

        if (!$this->isGranted("ROLE_ADMIN") && $this->getUser() !== $recipe->getUser()) {
            throw $this->createAccessDeniedException("Vous n'avez pas le droit de modifier cette recette");
        }

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recipe_delete", methods={"DELETE"})
     * @IsGranted("ROLE_USER")
     */
    public function delete(Request $request, Recipe $recipe): Response
    {
        // Vérifier si l'utilisateur connecté est admin ou si c'est lui qui a créé la recette
        if (!$this->isGranted("ROLE_ADMIN") && $this->getUser() !== $recipe->getUser()) {
            throw $this->createAccessDeniedException("Vous n'avez pas le droit de supprimer cette recette");
        }

        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($recipe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('recipe_index');
    }
}

templates/recipe/_card.html.twig
<article>
	<a href="{{ path('recipe_show', {'slug': recipe.slug}) }}">
		<img src="{{ asset('uploads/' ~ recipe.picture) }}" alt="{{ recipe.title}}" class="img-responsive">
	</a>
	<h2><a href="{{ path('recipe_show', {'slug': recipe.slug}) }}">{{ recipe.title }}</a></h2>
	<footer>
		<div class="label"><a href="#" class="like"><i class="fa fa-heart"></i></a> 12</div>
		<div class="label">
			<i class="fa fa-cutlery"></i>
			<a href="{{ path('category_show', {'slug': recipe.category.slug}) }}">
				{{ recipe.category.label }}
			</a>
			{% for tag in recipe.tags %}
			<a href="{{ path('tag_show', {'slug': tag.slug}) }}">
				#{{ tag.label}}
			{% endfor %}
			</a>
		</div>
			<div class="label">
				<i class="fa fa-user"></i>
				{{ recipe.user.pseudo }}
			</div>



	</footer>
</article>

templates/recipe/_delete_form.html.twig
<form method="post" action="{{ path('recipe_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipe{% endblock %}

{% block body %}
    <h1>Edit Recipe</h1>

    {{ include('recipe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('recipe_index') }}">back to list</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe index{% endblock %}

{% block body %}
    <h1>Recipe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>BakingTime</th>
                <th>PreparationTime</th>
                <th>NbPersonne</th>
                <th>Picture</th>
                <th>CreatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.id }}</td>
                <td>{{ recipe.title }}</td>
                <td>{{ recipe.bakingTime ? recipe.bakingTime|date('H:i:s') : '' }}</td>
                <td>{{ recipe.preparationTime ? recipe.preparationTime|date('H:i:s') : '' }}</td>
                <td>{{ recipe.nbPersonne }}</td>
                <td>{{ recipe.picture }}</td>
                <td>{{ recipe.createdAt ? recipe.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('recipe_show', {'slug': recipe.slug}) }}">show</a>
                    <a href="{{ path('recipe_edit', {'id': recipe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('recipe_new') }}">Create new</a>
{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipe{% endblock %}

{% block body %}
    <h1>Create new Recipe</h1>

    {{ include('recipe/_form.html.twig') }}

    <a href="{{ path('recipe_index') }}">back to list</a>
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent () }} - {{recipe.title}}{% endblock %}

{% block headerImage %}{{ asset('uploads/' ~ recipe.picture) }}{% endblock %}
{% block headerTitle %}{{ recipe.title }}{% endblock %}

{% block body %}
    <main class="container">

        <section class="row">
            <div class="col-md-4">
                <img src="{{ asset('uploads/' ~ recipe.picture) }}" alt="{{ recipe.title}}" class="img-responsive">
                <div class="label"><a href="#" class="like"><i class="fa fa-heart"></i></a> 42</div>
                <div class="label"><i class="fa fa-cutlery"></i>{{ recipe.category.label}}</div>
                <div class="label"><i class="fa fa-user"></i> Etienne H.</div>
                <ul style="">
                    {% for tag in recipe.tags%}
                        <a href="{{ path('tag_show', {'slug': tag.slug}) }}">
                        <li> #{{ tag.label }} </li> </a>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4">

                <ul>
                    {#todo ajouter methodes dans recipe pour retourner les temps formatés #}
                    <li>Temps de préparation : {{ recipe.preparationTimeFormatted}}</li>
                    <li>Temps de cuisson : {{ recipe.bakingTimeFormatted }}</li>
                </ul>
                <ul>
                    {% for step in recipe.steps  %}
                    <li>{{ step.number }} : {{ step.description }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4">
                <h2>Ingrédients</h2>
                <ul>
                    {% for recipeIngredient in recipe.recipeIngredients %}
                    <li>{{ recipeIngredient.ingredient.label }} : {{ recipeIngredient.quantity}} {{ recipeIngredient.unit.label }}</li>
                    {% endfor %}
                </ul>
            </div>
        </section>



    </main>
{% endblock %}